#lang racket

(provide set-size)
(provide scale-sprite)
(provide random-dec)
(provide random-size)
(provide set-color)
(provide change-color-by)
(provide random-color)
(provide random-tint)

(require 2htdp/image)
(require "../game-entities.rkt")
(require "../components/animated-sprite.rkt")
(require "./rgb-hsb.rkt")
;(require "../ai.rkt")

(require posn)

(define (set-size amount sprite)
  (lambda (g e)
    (define frames (animated-sprite-frames sprite))
    (define rate (animated-sprite-rate (get-component e animated-sprite?)))
    (define new-list (map (curry scale amount) (vector->list frames)))
    (define resized-sprite (new-sprite new-list rate))
    (define new-bb (image->bb (render resized-sprite)))
    (update-entity (update-entity e animated-sprite? (new-sprite new-list rate))
                   bb?
                   new-bb)))

(define (scale-sprite amount)
  (lambda (g e)
    (define frames (animated-sprite-frames (get-component e animated-sprite?)))
    (define rate (animated-sprite-rate (get-component e animated-sprite?)))
    (define new-list (map (curry scale amount) (vector->list frames)))
    (define resized-sprite (new-sprite new-list rate))
    (define new-bb (image->bb (render resized-sprite)))
    (update-entity (update-entity e animated-sprite? (new-sprite new-list rate))
                   bb?
                   new-bb)))

(define (random-dec min max)
  (define new-min (exact-round (* min 100)))
  (define new-max (exact-round (* max 100)))
  (/ (random new-min (add1 new-max)) 100))

(define (random-size min max sprite)
  (lambda (g e)
    (define frames (animated-sprite-frames sprite))
    (define rate   (animated-sprite-rate (get-component e animated-sprite?)))
    (define new-min (exact-round (* min 100)))
    (define new-max (exact-round (* max 100)))
    (define new-list (map (curry scale (/ (random new-min (add1 new-max)) 100)) (vector->list frames)))
    (define resized-sprite (new-sprite new-list rate))
    (define new-bb (image->bb (render resized-sprite)))
    (update-entity (update-entity e animated-sprite? (new-sprite new-list rate))
                   bb?
                   new-bb)))

(define (change-color-by amount)
  (lambda (g e)
    (define frames (animated-sprite-frames (get-component e animated-sprite?)))
    (define rate (animated-sprite-rate (get-component e animated-sprite?)))
    (define new-list (map (curry change-img-hue amount) (vector->list frames)))
    (update-entity e animated-sprite? (new-sprite new-list rate))))

(define (set-color amount sprite)
  (lambda (g e)
    (define frames (animated-sprite-frames sprite))
    (define rate   (animated-sprite-rate (get-component e animated-sprite?)))
    (define new-list (map (curry change-img-hue amount) (vector->list frames)))
    (update-entity e animated-sprite? (new-sprite new-list rate))))

(define (random-color min max)
  (lambda (g e)
    (define frames (animated-sprite-frames (get-component e animated-sprite?)))
    (define rate   (animated-sprite-rate (get-component e animated-sprite?)))
    (define hue-change (random min max))
    (define new-list (map (curry change-img-hue hue-change) (vector->list frames)))
    (update-entity e animated-sprite? (new-sprite new-list rate))))

(define (random-tint sprite)
  (lambda (g e)
    (define frames (animated-sprite-frames sprite))
    (define rate   (animated-sprite-rate (get-component e animated-sprite?)))
    (define random-color (make-color-hue (random 255) 255))
    (define new-list (map (curry tint-img random-color) (vector->list frames)))
    (update-entity e animated-sprite? (new-sprite new-list rate))))